---
title: Taking the Plunge into 0's and 1s Redux
author: ''
date: '2021-02-17'
slug: learning-data-science-and-entering-the-field
draft: true 
categories: []
tags: 
  - learning data science
  - self taught
  - python
  - r
 
header:
  caption: ''
  image: ''
---



Hello everyone! Long time no chat. Thank you for making it over to my new official website. For those of you who have read my [medium blog](https://medium.com/the-data-logs), welcome back. If you're new to my writing, welcome aboard. 

My name is Kerry Benjamin. In January 2020 I graduated as 1 of 16 people in Galvanize's Data Analyst program. But years before that, I have been learning data science on my own and have been blogging about my journey. I will continue to do that here on my new website, named after my original blog. I started a website because I wanted to have full ownership over my content. As to my old blog,  I may or may not delete it. Or just write updated posts here. Time will tell.

A lot has happened to me since I have started blogging way back in 2016. New skills( like python), new experiences(hackathon), new interests(airflow), etc. I plan to write about them here. The Data Logs main purpose is to document my journey learning about and entering the field of data science. I also hope that some of my articles can be helpful for new and aspiring people trying to enter the field. My path is very munch non-traditional and I want you all to know that's ok. 

So with all of that I'd like to say, take the plunge into 0's and 1's with me yet again. I hope you enjoy.